// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7GPXQ2T4zjhem7jf9X98yVEZmDjiUhPM',
    appId: '1:1074849638241:web:60c59a457c259f1d450720',
    messagingSenderId: '1074849638241',
    projectId: 'nutrixense-96382',
    authDomain: 'nutrixense-96382.firebaseapp.com',
    storageBucket: 'nutrixense-96382.firebasestorage.app',
    measurementId: 'G-F7795TKKZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcxAjQmQZylQIluzDHBgswejWbQ03ANHY',
    appId: '1:1074849638241:android:dd69f48f93f6aaf9450720',
    messagingSenderId: '1074849638241',
    projectId: 'nutrixense-96382',
    storageBucket: 'nutrixense-96382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtnF4lXicYGbVxMAozCzozEOWSfoDTj2k',
    appId: '1:1074849638241:ios:b25029b97e858bc8450720',
    messagingSenderId: '1074849638241',
    projectId: 'nutrixense-96382',
    storageBucket: 'nutrixense-96382.firebasestorage.app',
    iosBundleId: 'com.example.nutrixense',
  );
}
